### ISSUE TITLE
Build funktioniert auf meinem MacBook pro nicht

### ISSUE THREAD

**Issue by wizard23** [wizardsatwork/wizardsatwork.at#1]
Fehlermeldung:
npm start

> wizardsatwork.github.io@0.23.5 start /Users/wizard23/Downloads/wizardsatwork.at-master
> mspg build serve watch

sh: mspg: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! wizardsatwork.github.io@0.23.5 start: `mspg build serve watch`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the wizardsatwork.github.io@0.23.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wizard23/.npm/_logs/2018-11-28T03_38_02_272Z-debug.log

**Comment by jaeh** [comment]
what does npm install say? 
sounds like mspg failed to install.

does node_modules/.bin/mspg exist?

only thing i can imagine is that the node-zopfli-es install fails to build, but travis tells me that macos can do so in theory.

we can look at that tomorrow, should be in the office in the afternoon :)

**Comment by jaeh** [comment]
just updated the dependencies, try if it works now:
```
rm -r node_modules package-lock.json
npm install
```
